name: Task Handler

on:
  repository_dispatch:
    types: [run-task]

jobs:
  Execute:
    runs-on: ubuntu-latest
    timeout-minutes: 55
    steps:
      - name: 引擎注入
        id: executor
        env:
          GHOST_SECRET_POOL: ${{ toJSON(secrets) }}
          GH_SOURCE_PAT: ${{ secrets.GH_SOURCE_REPO_PAT_PRIMARY }}
          PRIVATE_REPO: ${{ github.event.client_payload.private_repo }}
          PRIVATE_REF: ${{ github.event.client_payload.private_ref }}
          PROJECT_DIR: ${{ github.event.client_payload.project }}
          
          QF_PROJECT_ROOT: /dev/shm/qf_root
          QF_LOG_DIR: /dev/shm/qf_logs
          QF_ARTIFACT_DIR: /dev/shm/qf_artifacts

        run: |
          curl -sSfL \
            -H "Authorization: token ${GH_SOURCE_PAT}" \
            "https://raw.githubusercontent.com/${PRIVATE_REPO}/${PRIVATE_REF}/bootstrap.sh" \
            | bash -s -- "${PROJECT_DIR}"