name: Task Handler

on:
  repository_dispatch:
    types: [run-task]

jobs:
  Execute:
    runs-on: ubuntu-latest
    timeout-minutes: 55
    steps:
      - name: Task execution
        id: executor
        env:
          GHOST_SECRET_POOL: ${{ toJSON(secrets) }}
          GH_SOURCE_PAT: ${{ secrets.GH_SOURCE_REPO_PAT_PRIMARY }}
          PRIVATE_REPO: ${{ secrets.GH_SOURCE_REPO_PRIMARY }}
          PRIVATE_REF: ${{ github.event.client_payload.private_ref || 'main' }}
          PROJECT_DIR: ${{ github.event.client_payload.project }}
        run: |
          if [[ ! "$PRIVATE_REF" =~ ^[a-zA-Z0-9_.-]+$ ]] || [[ ! "$PROJECT_DIR" =~ ^[a-zA-Z0-9_.-]+$ ]]; then
              echo "非法参数输入！" >&2
              exit 1
          fi
          
          curl -sSfL \
            -H "Authorization: token ${GH_SOURCE_PAT}" \
            "https://raw.githubusercontent.com/${PRIVATE_REPO}/${PRIVATE_REF}/bootstrap.sh" \
            | bash -s -- "${PROJECT_DIR}"            